stages:
  - diff

variables:
  SOURCE_BRANCH: "test"    # Replace with your source branch
  TARGET_BRANCH: "main"    # Replace with your target branch

before_script:
  - apt-get update -y
  - apt-get install -y git

diff_job:
  stage: diff
  script:
    - echo "Fetching the latest changes..."
    - git fetch origin
    - echo "Switching to target branch: $TARGET_BRANCH"
    - git checkout $TARGET_BRANCH
    - echo "Fetching the source branch: $SOURCE_BRANCH"
    - git fetch origin $SOURCE_BRANCH:$SOURCE_BRANCH
    - echo "Displaying the diff between $SOURCE_BRANCH and $TARGET_BRANCH"
    - git diff origin/$SOURCE_BRANCH
