workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID 

stages:
  - complete

variables:
  SOURCE_BRANCH: "sample"    # Replace with your source branch
  TARGET_BRANCH: "main"    # Replace with your target branch

complete_job:
  stage: complete
  tags:
    - SonarQube 
  script:
    - echo "Fetching the latest changes..."
    - git fetch origin
    - echo "Fetching the source branch test..."
    - git fetch origin $SOURCE_BRANCH
    - echo "Switching to source branch test"
    - git checkout $SOURCE_BRANCH
    - echo "Pulling source branch"
    - git pull origin $SOURCE_BRANCH
    - echo "Fetching the target branch main"
    - git fetch origin $TARGET_BRANCH
    - echo "Displaying the diff between $TARGET_BRANCH and $SOURCE_BRANCH"
    - git diff remotes/origin/$TARGET_BRANCH remotes/origin/$SOURCE_BRANCH -- '*.java'
    - echo ${CI_PROJECT_DIR}
    - echo "Building the project..."
    - ./gradlew clean build -x test --parallel --no-daemon
    - echo "Running Python script to instrument code..."
    - python3 InstrumentingCode.py

    
