workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID

stages:
  - complete

complete_job:
  stage: complete
  tags:
    - $SONARQUBE_TAG
  script:
    - echo "Fetching the latest changes..."
    - git fetch origin
    - echo "Fetching the SOURCE branch..."
    - git fetch origin $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - echo "Switching to SOURCE branch "
    - git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - echo "Pulling SOURCE branch"
    - git pull origin $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - echo "Fetching the TARGET branch "
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - echo "Displaying the diff between $CI_MERGE_REQUEST_TARGET_BRANCH_NAME and $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - git diff remotes/origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME remotes/origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -- '*.java'
    - echo ${CI_PROJECT_DIR}
    - echo "Building the project..."
    - ./gradlew clean build -x test --parallel --no-daemon
    - echo "Running Python script to instrument code..."
    - python3 InstrumentingCode.py

    
