stages:
  - complete

variables:
  SOURCE_BRANCH: "test"    # Replace with your source branch
  TARGET_BRANCH: "main"    # Replace with your target branch

complete_job:
  stage: complete
  tags:
    - SonarQube 
  script:
    - echo "Fetching the latest changes..."
    - git fetch origin
    - echo "Switching to source branch test"
    - git checkout $SOURCE_BRANCH
    - echo "Fetching the target branch main"
    - git fetch origin $TARGET_BRANCH
    - echo "Displaying the diff between $SOURCE_BRANCH and $TARGET_BRANCH"
    - git diff remotes/origin/$TARGET_BRANCH remotes/origin/$SOURCE_BRANCH -- '*.java'
    - echo ${CI_PROJECT_DIR}
    - echo "Building the project..."
    - ./gradlew clean build --info
    - echo "Running Python script to instrument code..."
    - python3 InstrumentingCode.py

    
