stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - # Add your build commands here

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - # Add your test commands here

deploy-job:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - # Add your deployment commands here
  only:
    - master
